# Generated by Django 3.2 on 2023-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cashback',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Кешбек'),
        ),
    ]
