# Generated by Django 3.2 on 2023-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_taste_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название абонемента')),
                ('img', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Изображение абонемента')),
                ('description', models.CharField(max_length=120, verbose_name='Описание абонемента')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
