# Generated by Django 3.2 on 2023-06-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20230618_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИ')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.abonements', verbose_name='Выберите абонемент')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
    ]
