# Generated by Django 3.2 on 2023-06-20 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='taste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.taste', verbose_name='Вкус'),
            preserve_default=False,
        ),
    ]
