# Generated by Django 3.2 on 2023-05-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_products_cashback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taste',
            options={'verbose_name': 'Вкус', 'verbose_name_plural': 'Вкусы'},
        ),
    ]
